Add multi_hitsounds
rafalh/dashfaction pull request #158
Opened 2021-09-05 08:55 UTC by is-this-c

2021-09-11 14:47 UTC, rafalh commented on game_patch/multi/server.cpp
> +                 if (pdata.multi_hitsounds == 2) {
enum > magic constant

2021-09-11 14:47 UTC, rafalh commented on common/src/config/GameConfig.cpp
> +    result &= visitor(dash_faction_key, "multi_hitsounds", multi_hitsounds);
keep registry key naming convention

2021-09-11 14:48 UTC, rafalh commented on common/include/common/config/GameConfig.h
> +    CfgVar<bool> multi_hitsounds = true;
Add some description in README about those modes because i'm not sure how this feature works currently

2021-09-11 14:49 UTC, rafalh commented on game_patch/multi/network.cpp
> +            custom_packets::process_packet(data + offset, len, addr, player);
it would be better if this could be not repeated - maybe use something like `bool processed = false; if PF: processed = ...`

2021-09-11 14:51 UTC, rafalh commented on game_patch/multi/server.cpp
> +                    custom_packets::send_hitsound_packet(killer_player);
why do we need a new packet for hitsound?

2021-09-11 14:58 UTC, rafalh requested changes

2021-09-11 14:58 UTC, rafalh commented on game_patch/multi/server.cpp
> +            else if (g_additional_server_config.hit_sounds.enabled) {
I want more configuration for the server owners so they can force hitsounds disabled, no matter what the client configured.
3 server-side modes: enable, disable, force disabled (naming suggestion, can be changed)
3 client-side modes: auto (use server setting), enable (if not forced disabled on the server), disable

2021-09-11 14:58 UTC, rafalh commented on game_patch/multi/custom_packets.cpp
> +        rf::snd_play_3d(29, position, 1.0f, rf::zero_vector, 0);
Currently sound id is configurable on the server. I'd like it to stay this way.

2025-02-24 05:37 UTC, is-this-c commented
Closing due to AF's damage notifications which may be a better path forward.

2025-02-24 05:37 UTC, closed without merging